In [2]:
import numpy as np
a=np.array([2,3,4])
a

array([2, 3, 4])

In [3]:
b=np.array([[2,3,4],[1,5,8]])
b

array([[2, 3, 4],
       [1, 5, 8]])

In [4]:
c=np.identity(5)
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
d=np.full((2,3),44)
d

array([[44, 44, 44],
       [44, 44, 44]])

In [12]:
e=np.random.rand(3,4)
e

array([[0.68958597, 0.47859115, 0.81060258, 0.69602946],
       [0.84256835, 0.12961184, 0.75022654, 0.07206692],
       [0.42936807, 0.32252373, 0.46973599, 0.14855187]])